#!/usr/bin/env python3
"""Turn the offline judge run (materials/ai-judge-labels.json) into assets/triage-judge.js (json.dumps)."""
import json, sys
src, dest = sys.argv[1], sys.argv[2]
j = json.load(open(src))
out = {"model": j["model"], "runner": j["runner"] + " 0.34.4", "options": j["options"], "date": j["date"],
       "note": "Produced offline, once, by materials/run-ai-judge.py; replayed in the page as data. No model runs in the browser.",
       "labels": [{"i": x["i"], "label": x["label"]} for x in j["labels"]]}
open(dest, "w").write("/* triage-judge.js - generated by materials/ship-judge.py with json.dumps. Do not edit by hand. */\n"
                      "window.TRIAGE_JUDGE = " + json.dumps(out, separators=(",", ":")) + ";\n")
print(len(out["labels"]), "labels", sum(x["parsed"] for x in j["labels"]), "parsed")
